### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
The result is that the overall document looks much more organised with proper formatting for the corresponding context.
The overall document structure with headings is also improved as can be seen in the following screenshot:

image

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
ping @psemiletov

**Comment by psemiletov** [comment]
Thanks a lot!

**Comment by yashpalgoyal1304** [comment]
waow: https://github.com/psemiletov/tea-qt/compare/c7be159..6aec580#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 

😆🤣

**Comment by psemiletov** [comment]
Yes, because I remembered that readme.md must looks normal as the plain text, so "bash" tags aren't good :(

**Comment by yashpalgoyal1304** [comment]
there are many things i like to say:
1. first and foremost, i am not pushing for merging my changes or anything like that, i hope it doesn't feel like that either. i am just discussing here. so, following are my thoughts:

----- 

> because I remembered that

* i was kinda a bit worried - that first, u merged it, then reverted those changes - so, it created more work FOR YOU. whereas there might be better ways to deal with this which could have saved your effort as well.

like if some proposed changes are not good then:
1. you could have commented wit the concerns that this and this thing is not good and will not work
2. the pr author (in this case me) will most likely respond - either with some new proposal, or their acceptance that the pr can be closed

-----

> must looks normal as the plain text, so "bash" tags aren't good :(

for this, i made other changes which worked on normal plain text too - so, i guess that while attempting to address the above concern, you actually reverted those changes too

again, i am not pushing for those, i just feel that this could have been much better handled with discussion.

-----

anyways, it's totally fine. awesome what works for you. take care.

**Comment by psemiletov** [comment]
README.md in TEA plays two roles - github's README.md, and "standard" README from the common tarball. When you made the commit, I thinked that it's fine, because it looked good. And I've merged the commit. But then I remembered the dual neture of TEA's README.md...

**Comment by yashpalgoyal1304** [comment]
ahw ohkay ohkay. got it.

can u share the rendered output of <code>"standard" README from the common tarball</code> ??

**Pull request merged**
